//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;

    [Serializable]
    public partial class List
    {
        public List()
        {
            this.Person = new HashSet<Person>();
        }
    
        public int listId { get; set; }
        public short knownPersonQuantity { get; set; }
        public short unknownPersonQuantity { get; set; }
    
        public virtual ICollection<Person> Person { get; set; }
    }
}
