//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;

    [Serializable]
    public partial class Mother
    {
        public Mother()
        {
            this.Person = new HashSet<Person>();
        }
    
        public int motherId { get; set; }
        public bool motherKnown { get; set; }
        public string mFirstName { get; set; }
        public string mLastName { get; set; }
        public string mGivenName { get; set; }
    
        public virtual ICollection<Person> Person { get; set; }
    }
}
